### ISSUE TITLE
"adsbygoogle.push() error: Only one 'enable_page_level_ads' allowed per page."

### ISSUE THREAD

**Issue by trongcong** [nuxt-community/google-adsense-module#56] opened 2020-04-16 13:56 UTC
I have use google-adsense-module in my nuxt project.
But ads don't display and an error appears.
Anything to fix the problem?

![Screenshot_1](https://user-images.githubusercontent.com/14900620/79464651-8a8e9700-8024-11ea-82d9-06c3ed6bef04.png)

**Comment by tarunmangukiya** [comment] 2020-04-23 12:26
Same error!

**Comment by TheLearneer** [comment] 2020-05-26 16:03
+1 to the error...

**Comment by seosmmbusiness** [comment] 2020-06-09 00:58
+1

**Comment by HapLifeMan** [comment] 2020-06-19 11:18
Same here, it's flooding my Sentry reports, any idea @tmorehouse @pi0?

**Comment by rahulkumarsingh73690** [comment] 2020-08-27 14:55
Please help us @pi0

**Comment by rahulkumarsingh73690** [comment] 2020-08-29 15:32
> Please help us @pi0

@Atinux

**Comment by farnabaz** [comment] 2020-10-19 17:38
Sorry for the late response, could you create a reproduction project? or describe th senario?  
This error shows because there is two google-adsense script on the page.

**Comment by rahulkumarsingh73690** [comment] 2020-10-19 17:46
> Sorry for the late response, could you create a reproduction project? or describe th senario?
> This error shows because there is two google-adsense script on the page.

Yes, but when I use two ads on the signal page then this error came. I think nuxt adsense module calls the entire Adsense script on every single ad. 

Another issue is when the user navigates from one page to another page quickly ad does not show.

**Comment by HapLifeMan** [comment] 2020-10-19 18:41
Yep it's my opinion too (script called twice)!

Also, you should take a look at AdSense, I think that the ads code changed a little bit :)

**Comment by aayushgoyal** [comment] 2020-11-02 18:32
+1 to the error...

**Comment by farnabaz** [comment] 2020-12-18 09:01
This should fix in the latest beta release. [v1.3.0-rc.1](https://github.com/nuxt-community/google-adsense-module/releases/tag/v1.3.0-rc.1)

**Comment by farnabaz** [comment] 2020-12-23 11:25
This should fixed in [v1.3.0](https://github.com/nuxt-community/google-adsense-module/releases/tag/v1.3.0).  

Feel free to reopen the issue or ask any question 🙂

**Closed by farnabaz** 2020-12-23 11:25 UTC

**Comment by HapLifeMan** [comment] 2021-08-10 07:43
Coming back with 1.4.0 and I can see another error "Only one AdSense head tag supported per page".
<img width="943" alt="CleanShot 2021-08-10 at 09 42 25" src="https://user-images.githubusercontent.com/1854141/128828218-6b7aab5e-6478-4494-8354-4af01e2d37bf.png">

**Comment by rahulkumarsingh73690** [comment] 2021-08-10 08:28
> Coming back with 1.4.0 and I can see another error "Only one AdSense head tag supported per page".
> <img alt="CleanShot 2021-08-10 at 09 42 25" width="943" src="https://user-images.githubusercontent.com/1854141/128828218-6b7aab5e-6478-4494-8354-4af01e2d37bf.png">

+1

**Comment by amismailz** [comment] 2021-08-11 23:15
![Screenshot from 2021-08-12 01-13-39](https://user-images.githubusercontent.com/9459819/129115428-550a65d7-9dcf-4a55-8ad3-b65c8c6f9d1c.png)

**Comment by otezz** [comment] 2021-08-16 03:34
Hi @farnabaz, sorry for nagging you. Could you please reopen this issue? I'm using v1.4.0 and having this issue.

**Comment by JoeEarly** [comment] 2021-09-28 22:48
@farnabaz  Any movement on this yet?

**Comment by SwapnilSoni1999** [comment] 2021-12-07 21:48
Facing same
